cmdb/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017-12-5 0005 15:42
# @Author  : All is well
# @Site    : 
# @File    : urls.py
# @Software: PyCharm


from django.conf.urls import url,include
from cmdb import views

urlpatterns = [
    #云商
    url(r'^cloud_list/', views.cloud_list,name='cloud_list'),
    url(r'^cloud_add/', views.cloud_add,name='cloud_add'),
    url(r'^cloud_edit-(\d+)/', views.cloud_edit,name='cloud_edit'),
    url(r'^cloud_del/', views.cloud_del,name='cloud_del'),
    #项目
    url(r'^pro_list/', views.pro_list,name='pro_list'),
    url(r'^pro_add/', views.pro_add,name='pro_add'),
    url(r'^pro_edit-(\d+)/', views.pro_edit,name='pro_edit'),
    url(r'^pro_del/', views.pro_del,name='pro_del'),

    #主机
    url(r'^host_list-(?P<cloud_name_id>\d+)-(?P<project_name_id>\d+)-(?P<status>\d+)/', views.host_list,name='host_list'),
    url(r'^host_edit-(\d+)/', views.host_edit,name='host_edit'),
    url(r'^host_del/', views.host_del,name='host_del'),
    url(r'^host_add/', views.host_add,name='host_add'),
    url(r'^host_select_update/', views.host_select_update,name='host_select_update'),

    #数据库
    url(r'^sql_list-(?P<cloud_name_id>\d+)-(?P<project_name_id>\d+)-(?P<status>\d+)/', views.sql_list,name='sql_list'),
    url(r'^sql_edit-(\d+)/', views.sql_edit,name='sql_edit'),
    url(r'^sql_del/', views.sql_del,name='sql_del'),
    url(r'^sql_add/', views.sql_add,name='sql_add'),
    url(r'^sql_select_update/', views.sql_select_update,name='sql_select_update'),

    #资产收集
    url(r'^update_asset/', views.update_asset,name='update_asset'),

    url(r'^test/', views.test,name='test'),
]

esaymanager/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from userauth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index,name='index'),
    url(r'^$', views.user_login,name='user_login'),
    url(r'^logout/', views.user_logout,name='user_logout'),
    url(r'^change_password/', views.change_password,name='change_password'),
    url(r'^user_list/', views.user_list,name='user_list'),
    url(r'^user_audit/', views.user_audit,name='user_audit'),
    url(r'^user_add/', views.user_add,name='user_add'),
    url(r'^user_edit-(\d+)/', views.user_edit,name='user_edit'),
    url(r'^user_del/', views.user_del,name='user_del'),
    url(r'^user_group_list/', views.user_group_list, name='user_group_list'),
    url(r'^user_group_add/', views.user_group_add, name='user_group_add'),
    url(r'^user_group_del/', views.user_group_del, name='user_group_del'),
    url(r'^user_group_edit-(\d+)/', views.user_group_edit, name='user_group_edit'),
    url(r'^cmdb/',include('cmdb.urls')),
    url(r'^deploy/',include('deploy.urls')),
]

cmdb/models.py
from django.db import models


class Project(models.Model):

    '''项目信息'''

    name = models.CharField(max_length=32, unique=True, verbose_name='项目名称')
    area_choises = (
        (1,'大陆'),
        (2,'日韩'),
        (3,'欧美'),
    )
    area = models.SmallIntegerField(choices=area_choises, verbose_name='区域')
    people = models.CharField(max_length=32, verbose_name='负责人')
    comment = models.TextField(verbose_name='备注')
    def __str__(self):
        return self.name
    class Meta:
            default_permissions = ()
            permissions = (
                ('view_project', '查看项目'),
                ('edit_project', '管理项目'),
            )
            verbose_name = '项目管理'
            verbose_name_plural = verbose_name

class Cloud(models.Model):
    '''云平台信息'''
    name = models.CharField(max_length=32, unique=True, verbose_name='平台名称')
    address = models.CharField(max_length=200, verbose_name='平台地址')
    people = models.CharField(max_length=32, verbose_name='商务联系人')
    phone = models.CharField(max_length=32,verbose_name='联系电话')
    QQ_group = models.CharField(max_length=32,verbose_name='响应QQ群')
    comment = models.TextField(verbose_name='备注')
    def __str__(self):
        return self.name
    class Meta:
        default_permissions = ()
        permissions = (
            ('view_cloud', '查看云平台'),
            ('edit_cloud', '管理云平台'),
        )
        verbose_name = '云平台管理'
        verbose_name_plural = verbose_name

class Server(models.Model):
    '''服务器信息'''
    status_choice = (
        (1, '上线'),
        (2, '下线'),
    )
    saltid = models.CharField(max_length=32,unique=True, verbose_name='SaltId')
    hostname = models.CharField(max_length=50, blank=True, verbose_name=u'主机名')
    lan_ip = models.GenericIPAddressField(null=True,blank=True,verbose_name='内网IP')
    wan_ip = models.GenericIPAddressField(unique=True,null=True,blank=True ,verbose_name='外网ip')
    osversion = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'系统版本')
    os = models.CharField(max_length=50,blank=True,null=True,verbose_name='操作系统')
    memory = models.CharField(max_length=50, blank=True, null=True, verbose_name='内存')
    disk = models.CharField(max_length=32, blank=True, null=True, verbose_name='硬盘')
    cpu_model = models.CharField(max_length=50, blank=True, null=True, verbose_name='CPU型号')
    cpu_core = models.SmallIntegerField(blank=True, null=True, verbose_name='CPU核数')
    kernel = models.CharField(max_length=50, blank=True, null=True, verbose_name='内核')
    area = models.ForeignKey("Area", blank=True, null=True, verbose_name='所在区域')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    status = models.SmallIntegerField(choices=status_choice, verbose_name='设备状态', default=0)
    project_name = models.ForeignKey('Project', max_length=50, blank=True, null=True, verbose_name='所属项目')
    cloud_name = models.ForeignKey('Cloud', max_length=50, blank=True, null=True, verbose_name='所属云平台')

    def __str__(self):
        return self.saltid
    class Meta:
        default_permissions = ()
        permissions = (
            ('view_server', '查看主机'),
            ('edit_server', '管理主机'),
        )
        verbose_name = '主机管理'
        verbose_name_plural = verbose_name

class DataBase(models.Model):
    '''数据库信息'''
    type_choice = (
        (1, 'MySQL'),
        (2, 'MongoDB'),
        (3, 'Memcached'),
    )
    status_choice = (
        (1, '上线'),
        (2, '下线'),
    )
    sql_name = models.CharField(max_length=32, unique=True, verbose_name='数据库名称')
    ip = models.GenericIPAddressField(verbose_name='IP')
    memory = models.CharField(max_length=32, blank=True, null=True, verbose_name='内存')
    disk = models.CharField(max_length=32, blank=True, null=True, verbose_name='硬盘')
    type = models.SmallIntegerField(choices=type_choice, verbose_name='类型')
    area = models.ForeignKey("Area", blank=True, null=True, verbose_name='所在区域')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    status = models.SmallIntegerField(choices=status_choice, verbose_name='设备状态', default=0)
    project_name = models.ForeignKey('Project', max_length=50, blank=True, null=True, verbose_name='所属项目')
    cloud_name = models.ForeignKey('Cloud', max_length=50, blank=True, null=True, verbose_name='所属云平台')

    def __str__(self):
        return self.sql_name
    class Meta:
        default_permissions = ()
        permissions = (
            ('view_database', '查看数据库'),
            ('edit_database', '管理数据库'),
        )
        verbose_name = '数据库管理'
        verbose_name_plural = verbose_name

class Area(models.Model):
    """资产所在区域"""
    region = models.CharField(max_length=32, unique=True, verbose_name="区域")
    def __str__(self):
        return self.region
    class Meta:
        default_permissions = ()
        permissions = (
            ('view_area', '查看区域'),
            ('edit_area', '管理区域'),
        )
        verbose_name = '地区'
        verbose_name_plural = verbose_name

class AssetRecord(models.Model):
    '''资产变更记录'''
    pass
    # user = models.CharField(max_length=244, verbose_name=u'用户')
    # audit_time = models.DateTimeField(auto_now_add=True, verbose_name=u'时间')
    # type = models.CharField(max_length=10, verbose_name=u'类型')
    # action = models.CharField(max_length=20, verbose_name=u'动作')
    # action_ip = models.CharField(max_length=15, verbose_name=u'用户IP')
    # content = models.TextField(verbose_name=u'内容')
    #
    # class Meta:
    #     default_permissions = ()
    #     permissions = (
    #         ("view_message", u"查看操作记录"),
    #         ("edit_message", u"管理操作记录"),
    #     )
    #     ordering = ['-audit_time']
    #     verbose_name = u'审计信息'
    #     verbose_name_plural = u'审计信息管理'

cmdb/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017-12-6 0006 15:12
# @Author  : All is well
# @Site    : 
# @File    : forms.py
# @Software: PyCharm

from django import forms
from .models import Cloud,Server,Project,DataBase


class CloudForm(forms.ModelForm):
    class Meta:
        model= Cloud
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'required','placeholder': '必填'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'required': 'required','placeholder': '必填'}),
            'people': forms.TextInput(attrs={'class': 'form-control', 'required': 'required','placeholder': '必填'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'required': 'required','placeholder': '必填'}),
            'QQ_group': forms.TextInput(attrs={'class': 'form-control', 'required': 'required','placeholder': '必填'}),
            'comment': forms.Textarea(attrs={'class': 'form-control','required': 'required','placeholder': '选填'}),
        }

class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = [
            'saltid','hostname','lan_ip','wan_ip',
            'osversion','memory','disk','cpu_model',
            'cpu_core','kernel','area','status','project_name','cloud_name',]

        widgets = {
            'saltid': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'hostname': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'lan_ip': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'wan_ip': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'osversion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '选填'}),
            'memory': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'disk': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'cpu_model': forms.TextInput(attrs={'class': 'form-control','placeholder': '选填'}),
            'cpu_core': forms.TextInput(attrs={'class': 'form-control',  'placeholder': '选填'}),
            'kernel': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '选填'}),
            'area': forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'status': forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'cloud_name': forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'project_name':forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
        }

class ProForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'area': forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'people': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
        }

class SqlForm(forms.ModelForm):
    class Meta:
        model = DataBase
        fields = [
            'sql_name','ip','memory','disk',
            'type','area','status','project_name','cloud_name',]

        widgets = {
            'sql_name': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'ip': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'memory': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'disk': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'type': forms.Select(attrs={'class': 'form-control', 'placeholder': '选填'}),
            'area': forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'status': forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'cloud_name': forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
            'project_name':forms.Select(attrs={'class': 'form-control', 'required': 'required', 'placeholder': '必填'}),
        }

templates/cmdb/cloud_add.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>资产管理
                        <small>添加云平台</small>
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form class="form-horizontal form-border" method="post" action="{% url 'cloud_add' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for row in form %}
                                <div class="item form-group">
                                    <label class="control-label col-md-2 col-sm-2 col-xs-12"
                                           style="text-align:left;">{{ row.label_tag }}</label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ row }}
                                        <div style="padding-top:10px;">
                                            {{ row.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div>
                                    <button id="send" type="submit" class="btn btn-primary pull-left">添加</button>
                                    <button type="reset" class="btn btn-success pull-left" onclick="res();">返回</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <!-- validator -->
        <script type="text/javascript" src="/static/js/validator.min.js"></script>
    <script>
        function res() {
            history.go(-1);
        }
    </script>


{% endblock %}

templates/cmdb/cloud_edit.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>资产管理
                        <small>修改云商</small>
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form class="form-horizontal form-border" method="post" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for row in form %}
                                <div class="item form-group">
                                    <label class="control-label col-md-2 col-sm-2 col-xs-12"
                                           style="text-align:left;">{{ row.label_tag }}</label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ row }}
                                        <div style="padding-top:10px;">
                                            {{ row.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div>
                                    <button id="send" type="submit" class="btn btn-primary pull-left">更新</button>
                                    <button type="reset" class="btn btn-success pull-left" onclick="res();">返回</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <!-- validator -->
        <script type="text/javascript" src="/static/js/validator.min.js"></script>
    <script>
        function res() {
            history.go(-1);
        }
    </script>


{% endblock %}

templates/cmdb/host_add.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>资产管理
                        <small>添加主机</small>
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form class="form-horizontal form-border" method="post" action="{% url 'host_add' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for row in form %}
                                <div class="item form-group">
                                    <label class="control-label col-md-2 col-sm-2 col-xs-12"
                                           style="text-align:left;">{{ row.label_tag }}</label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        {{ row }}
                                        <div style="padding-top:10px;">
                                            {{ row.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div>
                                    <button id="send" type="submit" class="btn btn-primary pull-left">添加</button>
                                    <button type="reset" class="btn btn-success pull-left" onclick="res();">返回</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <!-- validator -->
        <script type="text/javascript" src="/static/js/validator.min.js"></script>
    <script>
        function res() {
            history.go(-1);
        }
    </script>


{% endblock %}

templates/cmdb/host_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>资产管理
                        <small>主机详情</small>
                    </h2>
                    <!-- 右上角功能开关 -->
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a class="no-radius" href="#basic" aria-controls="basic" role="tab" data-toggle="tab">基本信息</a></li>
                        <li role="presentation"><a class="no-radius" href="#hardware" aria-controls="hardware" role="tab" data-toggle="tab">硬件信息</a></li>
                        <li role="presentation"><a class="no-radius" href="#log" aria-controls="log" role="tab" data-toggle="tab">变更记录</a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="basic">
                        {% include 'cmdb/host_basic_record.html' %}
                    </div>
                    <div role="tabpanel" class="tab-pane" id="hardware">
                        {% include 'cmdb/host_hardware_info.html' %}
                    </div>
                    <div role="tabpanel" class="tab-pane" id="log">
                        {#                        {% include 'asset/asset_log.html' %}#}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cmdb/pro_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block css %}
    <link href="{% static "css/dataTables.bootstrap.min.css" %}" rel="stylesheet">
    <style>
        .btn-default:hover{
            background-color: dodgerblue !important;
        }
        tr td,th{
            text-align: center;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <a href="{% url 'pro_add' %}" style="float:left;" class="btn btn-info btn-sm" role="button"><i class="fa fa-plus"></i></a>
                    <h2>资产管理
                    <small>项目列表</small>
                    </h2>

                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="x_title btn-group">
                        <button type="button" class="btn btn-sm btn-danger" id="del_select" style="float: left">删除所选</button>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12">

                        <div class="table-responsive">
                            <table id="datatable-buttons" class="table table-striped table-bordered table-hover table-condensed jambo_table bulk_action">
                                <thead>
                                    <tr>
                                        <th><input type="checkbox" id="check-all" class="flat"></th>
                                        <th>项目名称</th>
                                        <th>区域</th>
                                        <th>负责人</th>
                                        <th>备注</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody id="tb">
                                    {% for row in pro_obj %}
                                    <tr class="even pointer" id="{{ row.id }}">
                                        <td class="a center">
                                            <input type="checkbox" class="flat" name="table_records" value="{{ row.id }}">
                                        </td>
                                        <td>{{ row.name }}</td>
                                        <td>{{ row.get_area_display }}</td>
                                        <td>{{ row.people }}</td>
                                        <td>{{ row.comment }}</td>
                                        <td class=" last" style="text-align: center">
                                            <a class="btn btn-success btn-xs" href="#">查看</a>
                                            <a class="btn btn-warning btn-xs" href="/cmdb/pro_edit-{{ row.id }}">编辑</a>
                                            <button class="btn btn-danger btn-xs del_row">删除</button>
                                        </td>
                                    </tr>

                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- 单条删除确认 -->
    <div class="modal fade" id="delcfmModel">
  <div class="modal-dialog">
    <div class="modal-content message_align">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title">提示信息</h4>
      </div>
      <div class="modal-body">
        <p>您确认要删除吗？</p>
      </div>
      <div class="modal-footer">
         <input type="hidden" id="delNid"/>
         <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
         <a  id="DelConfirm" class="btn btn-success" data-dismiss="modal">确定</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
    <!-- 多条删除确认 -->
    <div class="modal fade" id="delSelect">
        <div class="modal-dialog">
            <div class="modal-content message_align">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">×</span></button>
                    <h4 class="modal-title">提示信息</h4>
                </div>
                <div class="modal-body" id="delinfo">
                    <p>您确认要删除吗？</p>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="delNid"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <a id="DelSelectConfirm" class="btn btn-success" data-dismiss="modal">确定</a>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

{% block js %}
    <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
    <!-- datatable button  -->
    <script src="{% static "js/dataTables.bootstrap.min.js" %}"></script>
    <script>


            $(function () {

                bindDel();
                bindDelConfirm();
                del_select();
                bindSelectDelConfirm();
                datatable_func();
            });

            function bindDel() {
                $("#tb").on('click','.del_row',function () {
                $("#delcfmModel").modal("show");
                var rowId = $(this).parent().parent().prop("id");
                $("#delNid").val(rowId);
            })
            }
            function bindDelConfirm() {
                var arr=[];
                $("#DelConfirm").click(function () {

                    var rowId = $("#delNid").val();
                    arr.push(rowId);
                    console.log(arr);
                    $.ajax({
                        url: '{% url 'pro_del' %}',
                        type: 'POST',
                        data: {'nid':arr},
                        success: function (arg) {
                            var dict = JSON.parse(arg);
                            if(dict.status){
                                swal({
                                  title: "Success!",
                                  text: "删除成功",
                                  type: "success",
                                  confirmButtonText: "OK"
                                });
                                $('tr[id="'+ rowId+'"]').remove()
                            }
                            $('#delcfmModel').modal('hide');
                        }
                    })
                })
            }
            function del_select() {
            arrdel = [];
            $("#del_select").click(function () {

                $("input[name='table_records']:checkbox").each(function () {
                    if (true == $(this).is(':checked')) {
                        arrdel.push($(this).val());
                    }
                });
                if(arrdel.length>0){
                    $("#delinfo").html("您确定要删除选中的"+arrdel.length+"条数据吗？");
                    $("#delSelect").modal('show');
                }
            })
        }
            function bindSelectDelConfirm() {
            delnum = arrdel;
            $("#DelSelectConfirm").click(function () {
                $.ajax({
                    url: '{% url 'pro_del' %}',
                    type: 'POST',
                    data:{'nid': delnum},
                    success: function (arg) {
                        var dict = JSON.parse(arg);
                        if(dict.status){
                            swal({
                                  title: "Success!",
                                  text: "删除成功",
                                  type: "success",
                                  confirmButtonText: "OK"
                                });
                            $("#tb tr.selected").remove();
                        }
                    }
                })
            })
        }
            function datatable_func() {
            $('#datatable-buttons').dataTable({
                bFilter: false,    //去掉搜索框方法三：这种方法可以
                bLengthChange: false,   //去掉每页显示多少条数据方法
                paging: false,
                bInfo: false
            });
        }

    </script>

{% endblock %}